### ISSUE TITLE
`parse` supposedly uses the command-line arguments when run with no inputs, but this is not the case 

### ISSUE THREAD

**Issue by jmetz** [iffy/nim-argparse#64]
Instead it's not possible to call no inputs - it seems from my (very limited) understanding so far of the code that it was implemented for `run` but not `parse`.

**Comment by casey-SK** [comment]
this issue still persists when argparse is installed via nimble. Maybe bump the version in the nimble file?

**Comment by casey-SK** [comment]
to be more descriptive, I noticed that this issue was occurring. So I ran `nimble install argparse` , which told me that I had version `2.0.0` and asked if I wanted to overwrite it, which I said yes to overwrite. And then it still did not work.

The workaround was to download the repo and run nimble install from there. Then the files in my nimble directory where updated to the latest in the repo, and the problem went away.

**Comment by iffy** [comment]
@casey-SK I just bumped argparse to v2.0.1 -- let me know if it doesn't work and sorry for the huge delay!
